name: githunt_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.0
  dio: ^5.5.0+1
  provider: ^6.1.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  get_it: ^7.7.0
  flutter_smart_dialog: ^4.9.7+7
  url_launcher: ^6.3.0
  flutter_secure_storage: ^9.2.2
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  timeago: ^3.6.1
  shared_preferences: ^2.2.3
  package_info_plus: ^8.0.0
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter_native_splash:
  color: "#A9A9A9"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/json/
