name: githunt_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.0
  yaml: ^3.1.2
  dio: ^5.4.3+1
  provider: ^6.1.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  get_it: ^7.7.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
